### ISSUE TITLE
[Question] How to check my data is secured ?

### ISSUE THREAD

**Issue by zedtux** [mCodex/react-native-sensitive-info#101]
I'm using this lib and I'd like to check that the data are stored securely on my iOS and Android devices.

What is the easiest way to do this?

**Comment by dtmp** [comment]
I was very surprised when I discovered that the data is not really protected

you can check it for android:

`
$ adb shell
$ run-as <app-package-name>
$ cd shared_prefs/
$ cat shared_preferences.xml
`

data is stored in unencrypted representation

**Comment by phyzalis** [comment]
I guess you need a rooted phone to do that ?

**Comment by dtmp** [comment]
> I guess you need a rooted phone to do that ?

I tested it on an emulator. only with remote debugging enabled.

maybe I don’t understand something, but having implemented my own module inspired by this [post](https://medium.com/@ericfu/securely-storing-secrets-in-an-android-application-501f030ae5a3), I saw encrypted data in the storage.

I look at the RNSensitiveInfoModule.java module and don’t understand how encryption is called without passing `touchID = true` in the options. Without passing this parameter from the `setItem` method, we get to the `putExtra` method, from which we write the value to shared_prefs without any encryption.

maybe I'm doing something wrong

**Comment by zedtux** [comment]
Hopefully @mCodex gives us an input about this topic?

**Comment by Marvedog** [comment]
This may be a little bit late, but I would recommend checking out the following resources for local storage security testing

- [Android](https://github.com/OWASP/owasp-mstg/blob/1.1.3/Document/0x05d-Testing-Data-Storage.md#testing-local-storage-for-sensitive-data-mstg-storage-1-and-mstg-storage-2)
- [iOS](https://github.com/OWASP/owasp-mstg/blob/1.1.3/Document/0x06d-Testing-Data-Storage.md#testing-local-data-storage-mstg-storage-1-and-mstg-storage-2)
