### ISSUE TITLE
TypeScript typings missing in "keystore" branch

### ISSUE THREAD

**Issue by davidfarinha** [mCodex/react-native-sensitive-info#104]
The bundled TypeScript typings [exist in the default branch](https://github.com/mCodex/react-native-sensitive-info/blob/master/index.d.ts), but not in the "keystore" branch. The typings need adding into this branch aswell.

**Comment by vspedr** [comment]
Hi @davidfarinha, PR #107 should address this issue. I'll take some time later to review the keystore branch and merge it into master if needed, I'm not even sure why it still exists

**Comment by davidfarinha** [comment]
Awesome, thanks. Also it was my understanding that the "keystore" branch differs from master (uses keystore instead of shared-prefs). Is this not correct? Are there any differences between these branches?

**Comment by vspedr** [comment]
https://github.com/mCodex/react-native-sensitive-info/compare/master...keystore?expand=1

Here we can see the diff between the two branches, and it looks like there's only a few fixes in master that are not in keystore, maybe it was merged at some point but not deleted.

@mCodex are we missing something here?
