### ISSUE TITLE
How to catch error ?

### ISSUE THREAD

**Issue by anhhtz** [mCodex/react-native-sensitive-info#105]
Hello,

How can I catch error (if occur)
```js
SInfo.getItem('key', {
            sharedPreferencesName: 'app',
            keychainService: 'app'
        }).then(value => console.log('val => ' + value))
            .catch(error => console.log('err => ' + error)) // is this catch is support ?
```

Thanks !

**Comment by jpodpro** [comment]
i have an issue where getItem doesn't resolve. in iOS after a period of inactivity and airplane mode when network returns the app runs and mounts in the background which calls getItem in my app. however the promise never resolves.

**Comment by afiller** [comment]
Were you able to solve this in an own fork or something, @jpodpro? We are facing the same problem in one of our projects.

**Comment by jpodpro** [comment]
@afiller i think we just worked around the issue by avoiding calling `SInfo.getItem` in the background context. looking at the code here it looks like we have restricted `SInfo.getItem` to the `componentDidMount` handler.
