### ISSUE TITLE
Delete and add back fingers on device not working on Android

### ISSUE THREAD

**Issue by AJM88** [mCodex/react-native-sensitive-info#114]
I'm currently using this library in a project for Android and IOS.
One of the requirements is to store some information behind fingerprint/faceid protection, so I have used this library.

So far all worked well apart from one scenario. I want the user to be able to delete all fingers and then add a new one and don't lose the access to the information saved on the secure storage. Currently, this is working on IOS and Android simulator, but not on real Android devices.

Steps to reproduce it:
- Add finger 1 to the device (if it is not already there)
- Open your app and call to setItem
- Try to do getItem, the fingerprint is requested and the value returned.
- Go to system settings > security > add a new finger, or remove all fingers and add a new/same finger
- Open your app and use getItem

Following that process on Android emulator, the value is returned.
On ios real device it is also working. This behaviour is defined by the `kSecAccessControl` defined
But on Android device is not returning me the item.

Is there anything similar to `kSecAccessControl` to set for android in order to make this work?

**Comment by AJM88** [comment]
I have found a solution to the problem.
Inside `RNSensitiveInfoModule.java` file in the section where `KeyGenParameterSpec.Builder` is created just by adding `builder.setInvalidatedByBiometricEnrollment(false);` it will solve the issue.

If we look at androids documentation https://developer.android.com/reference/android/security/keystore/KeyGenParameterSpec.Builder.html#setInvalidatedByBiometricEnrollment(boolean) it does explain what that flag actually means.

It will be a great option to include an extra property for Android to specify this option. At for some people, it will make more sense to invalidate the keys on enrollment.

I'll try to work on a PR if I have time after the project that I'm on is finished.

**Comment by mCodex** [comment]
Thanks man! I'll close the issue, but your PR is always welcome!

**Comment by AliakseiDouhal** [comment]
This problem still reproduce. Can anybody fix this? Thank you

**Comment by AJM88** [comment]
@AliakseiDouhal I just created a PR with the changes I proposed on my previous comment. [https://github.com/mCodex/react-native-sensitive-info/pull/138](https://github.com/mCodex/react-native-sensitive-info/pull/138).

Until @mCodex reviews it and decides if it is worth including it, you can try it from my GitHub fork. It'll be good as I haven't had time to test it, that is why I was taking time to publish it, but as I've seen that I'm not the only one trying the same thing I decided to put it so it can receive feedback from anyone.

**Comment by AliakseiDouhal** [comment]
> @AliakseiDouhal I just created a PR with the changes I proposed on my previous comment. #138.
> 
> Until @mCodex reviews it and decides if it is worth including it, you can try it from my GitHub fork. It'll be good as I haven't had time to test it, that is why I was taking time to publish it, but as I've seen that I'm not the only one trying the same thing I decided to put it so it can receive feedback from anyone.

It looks good @AJM88 . I think you should add @mCodex in reviewers in your PR, may be it will help him see PR sooner
