### ISSUE TITLE
Error verifyReleaseResources

### ISSUE THREAD

**Issue by cesarbecerra** [mCodex/react-native-sensitive-info#117]
When i try to compile my app for release i get the following error
`* What went wrong:
Execution failed for task ':react-native-sensitive-info:verifyReleaseResources'.
> com.android.ide.common.process.ProcessException: Failed to execute aapt`

**Comment by rborn** [comment]
add this in your `android/build.gradle` file (assuming you use these values for `compileSdkVersion` and `buildToolsVersion`)

~~~
subprojects {
    afterEvaluate {project ->
        if (project.hasProperty("android")) {
            android {
                compileSdkVersion 27
                buildToolsVersion  "27.0.3"
            }
        }
    }
}
~~~

**Comment by zedtux** [comment]
Thank you @rborn for your help on this. Am I right thinking that the code update, done 29 days ago, in [this lib's gradle file](https://github.com/mCodex/react-native-sensitive-info/blob/master/android/build.gradle) will solve this issue and we could then remove your dirty fix ?

**Comment by rborn** [comment]
@zedtux it should, you can try to install the git version and test

**Comment by mCodex** [comment]
Hello, v5.2.6 has been released and that error should be fixed by now. :)
