### ISSUE TITLE
Error: encrypted argument can't be null

### ISSUE THREAD

**Issue by tbsf** [mCodex/react-native-sensitive-info#119]
After https://github.com/mCodex/react-native-sensitive-info/pull/115 I'm getting

`{ [Error: encrypted argument can't be null] framesToPop: 1, code: 'EUNSPECIFIED' }`

when I call `SInfo.getItem('blah', {})`

Trying `SInfo.getItem('blah', {encrypt: true})` gave me the same result. Am I missing another argument?

**Comment by star-collector** [comment]
I made a new pull request - #120. Now **getItem** should return null if key/value pair never were set prior with **setItem** method just like the old keystore branch used to do.

About the **{ encrypt: true }** option - it never actually did anything even in the old version of keystore branch, despite being mentioned in **README.md**. I removed all mentions of it from **README** file in this pull request to prevent any confusion in the future.

**Comment by mCodex** [comment]
Hey man, thanks! Sorry for delaying you the answer.

**Comment by gusgard** [comment]
I'm having the same error but only happens with an Android Nexus5X - 8.1.0. Any reason why it is fails with that device and why? I'm in the last commit of the branch `keystore`. Thanks
