### ISSUE TITLE
react-native-sensitive-info:verifyReleaseResources error

### ISSUE THREAD

**Issue by LeDanielH** [mCodex/react-native-sensitive-info#121]
I have upgraded my app to the newest version of React Native 0.57.1 . Release build fails with the error `react-native-sensitive-info:verifyReleaseResources`. I have updated `node_modules/react-native-sensitive-info/android/build.gradle` `compileSdkVersion` from `25` to `26` and the `targetSdkVersion` from `25` to `26` and it fixed the build issue for me.

**Comment by mCodex** [comment]
Hello, v5.2.6 has been released and that error should be fixed by now. :)
