### ISSUE TITLE
On iOS, when using setItem on an undefined value, previous items are removed

### ISSUE THREAD

**Issue by RaphCayou** [mCodex/react-native-sensitive-info#128]
We found a problem that seems to occur only on iOS. When an undefined value is saved using setItem, previous values saved to keychain are removed. Values added after are saved as they should.

#### Adding values to keychain
```javascript
SInfo.setItem('valueThatWillNotAppear', 'thisValueDoesntSave', {});
SInfo.setItem('secondValueThatWillNotAppear', 'thisValueAlsoWontSave', {});
SInfo.setItem('valueThatIsUndefined', undefined, {});
SInfo.setItem('valueThatWillAppear', 'thisValueSaves', {});
SInfo.getAllItems({}).then(values => {
    return values;
});
```

#### Resulting keychain values
![image](https://user-images.githubusercontent.com/16038301/47500976-460cab80-d832-11e8-9b9a-0a64d11986c2.png)

Am I doing something wrong here? I know that I should verify that the value is not undefined but this behavior was definitely not expected.

**Comment by Kylar13** [comment]
Holy fucking shit, we just spent 4hours trying to figure out a VERY weird behavior, only to find out that the developer of this fucking library has not even spent the probably 2min that would take to solve this fucking issue. FUCKING FUCK

**Comment by EJohnF** [comment]
yea, also spend quite some time what's happening. Now need to add some surrounded checks.

**Comment by ItsNotEasyBeingGreen** [comment]
This is default Keychain behaviour.
