### ISSUE TITLE
Android  permissions marked as risky ?

### ISSUE THREAD

**Issue by ButuzGOL** [mCodex/react-native-sensitive-info#130]
I have run application with MobSf
and it gave us three issues based on permissions
- android.permission.WRITE_EXTERNAL_STORAGE
- android.permission.READ_PHONE_STATE
- android.permission.READ_EXTERNAL_STORAGE

![mobsf](https://user-images.githubusercontent.com/196564/48425449-88f4db80-e76d-11e8-9af0-3ccac66ead32.png)

**Comment by mCodex** [comment]
Can you explain more? RNSInfo only needs USE_FINGERPRINT. As you can see [here](https://github.com/mCodex/react-native-sensitive-info/blob/master/android/src/main/AndroidManifest.xml)

Maybe those authorizations are from React-Native, check [here](https://facebook.github.io/react-native/docs/removing-default-permissions)

**Comment by ButuzGOL** [comment]
sorry my search showed it in example page
