### ISSUE TITLE
[Question] - why SInfo is undefined

### ISSUE THREAD

**Issue by bennyh23** [mCodex/react-native-sensitive-info#134]
Hi, i'm trying to use this library for secured storage, when i try to use SInfo it says it undefined,
here is part of the code, am i miss something ?

```
import SInfo from 'react-native-sensitive-info';

return new Promise((resolve, reject) => {
      httpClient.post(ROUTE, {
        Email: email,
        Pass: pass,
      }).then((result) => {
        if (result.status === 200) {
          const token = result.headers["some-header"];
          SInfo.setItem('token',token , {});
});
```

**Comment by vspedr** [comment]
Hi @bennyh23, did you follow the [linking](https://github.com/mCodex/react-native-sensitive-info#linking-project) instructions from the README? The lib will not work if you skip this, as it depends on some native code.

**Comment by bennyh23** [comment]
i run 
react-native link react-native-sensitive-info
to link the package
