### ISSUE TITLE
Not restore information after reinstall application on android

### ISSUE THREAD

**Issue by abaddonGIT** [mCodex/react-native-sensitive-info#136]
Hi guys. I not restor my information after app reinstall. It works on ios (after resinstall app i can get my id from keychain) but not worked in android. 
manifest file:
`<application
      android:name=".MainApplication"
      android:label="@string/app_name"
      android:icon="@mipmap/ic_******_launcher"
      android:allowBackup="true"
      tools:replace="android:allowBackup"
      android:fullBackupContent="@xml/backup_rules"
      android:usesCleartextTraffic="true"
      android:theme="@style/AppTheme">`
rules file:
`<?xml version="1.0" encoding="utf-8"?>
<full-backup-content>
    
    <include
        domain="sharedpref"
        path="." />
</full-backup-content>`
Set item:
`const keychainOptions = {
  sharedPreferencesName: 'com.*****',
  keychainService: 'com.******',
  encrypt: true,
};
SInfo.setItem(key, JSON.stringify(value), keychainOptions);`
RN veriosn - 0.55.3
 react-native-sensitive-info version - 5.2.7

**Comment by samcampisi** [comment]
I would also like to persist the sensitive info after the app is uninstalled and reinstalled again. Is there a way of achieving this?
