### ISSUE TITLE
Cannot read property setItem of undefined

### ISSUE THREAD

**Issue by BenjErgizerBunny** [mCodex/react-native-sensitive-info#141]
I keep getting the error in the title above for iOS.  I've checked package.json to make sure "react-native-sensitive-info": "^5.3.0" is there.  I've also checked my Podfile and   pod 'react-native-sensitive-info', :path => '../node_modules/react-native-sensitive-info' is showing up.

I can launch successfully on Android without any issues using the exact code I've included below which matches example one provided on the GitHub page.

```
import React from 'react';
import { 
  StyleSheet, 
  AsyncStorage 
} from 'react-native';
import firebase from 'react-native-firebase';
import SInfo from 'react-native-sensitive-info';
import SplashScreen from 'react-native-splash-screen';
import AppContainer from './Components/BottomTabNav';

export default class App extends React.Component {
  constructor(props) {
    super();
    this.state = {
       userData: {}
    };
      SInfo.setItem('key1', 'value1', {
          sharedPreferencesName: 'mySharedPrefs',
          keychainService: 'myKeychain'
        }).then((value) =>
          console.log(value) //value 1
        )
  }
```
  

Does anyone have any suggestions?

**Comment by alainib** [comment]
same issue after just installed it (badly apparently)
i linked it but i have nothing in pod for this lib

any fix ? thanks

**Comment by JeffreyLeeDave** [comment]
So I've notice this issue on some other libraries as well. What I did was this.

1. yarn install to get the package
2. react native link
3. pod install
