### ISSUE TITLE
User interaction is not allowed

### ISSUE THREAD

**Issue by blolo** [mCodex/react-native-sensitive-info#144]
I'm seeing this error message "**User interaction is not allowed**" a lot when running my app:

1.  What is the proper way of using setItem method? this is what I' doing 
**rnsi.setItem(someKey, someEncryptedValue, {})**

2. What is the reason for this error?

**Comment by demchenkoalex** [comment]
For anyone facing this issue - take a look at the answer [here](https://stackoverflow.com/questions/9723949/ios-sfhfkeychainutils-failing-sometimes-with-error-25308-errsecinteractionnot). You are able to set keychain access attribute in the **options**, e.g.

```javascript
SInfo.setItem('key1', 'value1', {
  keychainService: 'myKeychain',
  kSecAttrAccessible: 'kSecAttrAccessibleAfterFirstUnlock',
  sharedPreferencesName: 'mySharedPrefs',
});
```
