### ISSUE TITLE
Face ID

### ISSUE THREAD

**Issue by maciejsaw** [mCodex/react-native-sensitive-info#147]
Thank you for a great lib. We used this in our app which enabled us a secure fingerprint login.

Is there a chance you could add a support for iOS Face ID?

**Comment by savelichalex** [comment]
Hi @maciejsaw , I already did it https://github.com/mCodex/react-native-sensitive-info/blob/master/ios/RNSensitiveInfo/RNSensitiveInfo.m#L37

@mCodex could I ask you to create new release please 😊

**Comment by mCodex** [comment]
Doing this right now 😄

**Comment by mCodex** [comment]
Done! 🤗  Released in 5.4.0 🎉

**Comment by Prophetaa** [comment]
@savelichalex  thanks for your addition, but how can I integrate face ID? By simply adding kSecAccessControl: "kSecAccessControlBiometryAny" to the options object?

Thanks in advance

**Comment by savelichalex** [comment]
@Prophetaa Hi! Yes, just like that. I'm also using `touchID: true`, don't remember actually why 😅

**Comment by Prophetaa** [comment]
@savelichalex Thanks for the quick reply! I've tried, however, my iPhone X simulator and real devices keep crashing on authentication, the screen goes black and the app dies. Has this ever occured to you?

**Comment by savelichalex** [comment]
@Prophetaa no, sorry. I didn't get part about authentication, does it occur before or after you had a chance to use FaceID (I mean, do you see a system alert for biometry authentication) ?

**Comment by Prophetaa** [comment]
@savelichalex That's the problem, it happens when the alert for biometry is supposed to show up, the screen goes black for a second and then the app crashes, then I get this on Xcode 
<img width="906" alt="Screen Shot 2019-09-10 at 10 34 58 AM" src="https://user-images.githubusercontent.com/38473739/64597840-e3bf8980-d3b6-11e9-802a-a4cf7054200d.png"> 
I went from version 5.2.7#keystore to 5.5.0 , is there any breaking changes? I'm so sorry for the trouble

**Comment by savelichalex** [comment]
It would be great if you did a sample project with this error, I'll try to take a look then.

**Comment by Prophetaa** [comment]
Good morning @savelichalex , sorry it took some time to get back I was a bit busy, anyway I managed to replicate the issue, I saved it here https://github.com/Prophetaa/rnsi-test, just git clone install the pods and run that baby on iOS. When you attempt to get items from the RNSI storage it dies if you're using faceID, touchID works fine :(

**Comment by savelichalex** [comment]
Hi @Prophetaa, unfortunately I don't have an X device right now, but I'll look as soon as I can, hope it won't be too long, sorry.

**Comment by Prophetaa** [comment]
Hey @savelichalex It also crashes in a simulator the same way, but surely take your time, thank you so much for the help <3

**Comment by Prophetaa** [comment]
UPDATE: @savelichalex  don't bother, I found the issue. I went to read the apple docs, and it turns out you need to declare a NSFaceIDUsageDescription key on the Info.plist file.  @mCodex Should we add this to the libraries Readme file?

**Comment by morrigan** [comment]
Hey guys, should a modal/dialog prompt when using `setItem` ? I am not getting it on using that method although storing works. Only on `getItem` I get the dialog prompt "Do you want to allow XY to use Face ID". Any suggestions here?

**Comment by Prophetaa** [comment]
Hey @morrigan , setItems does not require authentication, therefore it doesn't prompt the user, only getItem will ask for auth (finger or faceID) 😄

**Comment by morrigan** [comment]
@Prophetaa that's interesting! Ok, good to know (and maybe document).

**Comment by Prophetaa** [comment]
@mCodex can we close this issue? Obrigado <3

**Comment by mCodex** [comment]
Sure! Obrigado! 😉
