### ISSUE TITLE
Autolinking support 

### ISSUE THREAD

**Issue by Kida007** [mCodex/react-native-sensitive-info#155]
react-native 0.60.0 Introduces Autolinking , would be great to Implement it. 

PS:  (Following your Help-Wanted Note )I'm thinking of being a mini-maintainer of this library. Would help me learn stuff . let me know where to catch up ( an email or something ). Thanks for the great lib though

**Comment by dannydanzka** [comment]
Currently in reactio-native 0.60 when trying to install the pod libraries this error appears.

**CocoaPods could not find compatible versions for pod "react-native-sensitive-info":**

It would be fine if you are going to continue giving support.

Regards!

**Comment by Kida007** [comment]
already handled .
