### ISSUE TITLE
[Question] Android passcode fallback

### ISSUE THREAD

**Issue by driley-emoney** [mCodex/react-native-sensitive-info#159]
Since iOS allows a possible device code fallback, does this library allow the device code to be used instead of fingerprint in the case fingerprint is not setup? It seems like this may be possible through android keystore but a brief look at the android code here looks like fingerprint would be required for this to work.

Specifically, it appears if we set setUserAuthenticationValidityDurationSeconds then we can use device pincode screen.

**Comment by spawn-guy** [comment]
i am investigating exactly this functionality/fallback. 

but it seems that this feature is not available in the `FingerprintManager` that is used here, but it IS available with `BiometricManager`. which is the successor of deprecated `FingerprintManager` (This class was deprecated in API level 28)

so, the BiometricsManager has a BiometricsPromt builder (i.e. no need to create custom screens for fingerprint - shoulld work the same as with Apple). and that Builder has https://developer.android.com/reference/android/hardware/biometrics/BiometricPrompt.Builder.html#setDeviceCredentialAllowed(boolean)
> The user will first be prompted to authenticate with biometrics, but also given the option to authenticate with their device PIN, pattern, or password.

**Comment by spawn-guy** [comment]
i think this refactoring possibility should not be forgotten :/
