### ISSUE TITLE
androidx.annotation.NonNull

### ISSUE THREAD

**Issue by kbourchbane** [mCodex/react-native-sensitive-info#174]
in my project react-native I don't use androidx, and i have a lot of lib didn't use androidx, I have to delete the import line androidx.annotation.NonNull; in RNSensitiveInfoModule to work. any help please

**Comment by chrismoran-bkt** [comment]
Take a look at [this explanation of androidx](https://enappd.com/blog/androidx-react-native/83/). This is likely what will fix your issue.
