### ISSUE TITLE
can't get the store data by uninstall-install on android

### ISSUE THREAD

**Issue by cx5168** [mCodex/react-native-sensitive-info#179]
After uninstalling and reinstalling, the last saved data cannot be retrieved on android

react-native: 0.61.4
react-native-sensitive-info : 5.5.5

source:
import ShareInfo from 'react-native-sensitive-info';
const shareData = await ShareInfo.getItem('uniqueId', {
      sharedPreferencesName: 'share',
      keychainService: 'myKeychain',
    });
    if (!shareData) {
      const uniqueId = await DeviceInfo.getUniqueId();
      await ShareInfo.setItem('uniqueId', uniqueId, {
        sharedPreferencesName: 'share',
        keychainService: 'myKeychain',
      });
    }
have any way  to solve it?

**Comment by ripzery** [comment]
Isn't that a correct behavior? The data should be removed if the app is uninstalled, no?

**Comment by gusgard** [comment]
Are you using `android:allowBackup="false">` ? https://stackoverflow.com/a/35296675/2407880
