### ISSUE TITLE
isHardwareDetected() not working on iOS

### ISSUE THREAD

**Issue by HadiModarres** [mCodex/react-native-sensitive-info#193]
isHardwareDetected function works properly for Android; it returns true if device has the capability but user hasn't enrolled any fingerprints, but the method doesnt work the same for iOS.

Am I missing something?

**Comment by mCodex** [comment]
Hi,

I've investigated this problem and it occurs because somehow this method was not implemented in iOS. I would recommend you to use `isSensorAvailable` instead.

On next release `isHardwareDetected` will be removed.
