### ISSUE TITLE
Need Catalyst support

### ISSUE THREAD

**Issue by exotexot** [mCodex/react-native-sensitive-info#194]
Would appreciate Catalyst support. I can build for Catalyst without problems but I cannot store and retrieve data in my Catalyst app.

**Comment by exotexot** [comment]
Has anything happend on this front? I just made another build and I didn't encounter any problems related to 
react-native-sensitive-info

**Comment by mCodex** [comment]
> Has anything happend on this front? I just made another build and I didn't encounter any problems related to
> react-native-sensitive-info

No, I didn't 😅😅😅😅 I was reading about catalyst yesterday, but I haven't done anything yet 😅 I'm working on the [v6.0.0](https://github.com/mCodex/react-native-sensitive-info/releases/tag/v6.0.0)

However, did it work?

**Comment by exotexot** [comment]
Haha. Okay whatever, I'll take it 👍 
I just double checked and I can see my token successfully being stored in the keychain.

I remember recieving errors at least while running the app - possibly also while building in xcode - on catalyst 2 months ago. I had to remove the entire library back then. Now it just works!

**Comment by exotexot** [comment]
I'm running on 5.5.6 btw.

**Comment by exotexot** [comment]
For anyone experiencing this error:
Error: The operation couldn’t be completed. (OSStatus error -34018.)]

see this stackoverflow: https://stackoverflow.com/questions/27752444/ios-keychain-writing-value-results-in-error-code-34018
