### ISSUE TITLE
Android showModal?

### ISSUE THREAD

**Issue by dhussong** [mCodex/react-native-sensitive-info#201]
In the documentation (https://mcodex.dev/react-native-sensitive-info/docs/android_options), it states that "when showModal is true, an Android native prompt will show up ...". Where is "showModal" used? How do I set it to true?

**Comment by mCodex** [comment]
@dhussong you can use it in:

```javascript
setItem('key', 'value', {
... 
touchID: true, 
showModal: true
}) ;
```

Or

```javascript
getItem('key', {
... 
touchID: true, 
showModal: true
}) ;
```

I'm so sorry docs are being still developed

**Comment by dhussong** [comment]
Not a problem. Thank you for the quick reply!
