### ISSUE TITLE
setInvalidatedByBiometricEnrollment invalid arguments

### ISSUE THREAD

**Issue by samuelasd** [mCodex/react-native-sensitive-info#203]
Hi,

I'm trying to call the method SInfo.setInvalidatedByBiometricEnrollment(false); but I'm receiving the following error:

![imagen](https://user-images.githubusercontent.com/19672138/85422160-45ff0a80-b543-11ea-8369-0b32d1616682.png)

Im using RN 0.61.5 and react-native-sensitive-info": "5.5.5"

What Am I doing wrong?

**Comment by mCodex** [comment]
Hello, it is really strange. 

It can be a bug I'll try to debug it.

**Comment by samuelasd** [comment]
> 
> 
> Hello, it is really strange.
> 
> It can be a bug I'll try to debug it.

Thanks, if you need aditional info just tell me

**Comment by mCodex** [comment]
Released in 5.5.7 😄
