### ISSUE TITLE
Error with setItem after Biometrics are added (invalidated)

### ISSUE THREAD

**Issue by jambanagar** [mCodex/react-native-sensitive-info#204]
Bug:

Android:

1. Remove all fingerprints on the device
2. Clear the app cache and open the app (make sure the SInfo is imported in the activity)
3. Since there is no fingerprint, we thrown an alert to user to add fingerprints.
4. Add a fingerprint on the device
5. Go back to app and try to SInfo.setItem it throws a crypto error

It looks like once SInfo generates a key in Android keystore, it tries to re-use the same key everytime. There is no interface call to  delete and reinitialize the key in Android keystore after the fingerprint is invalidated.

Please help!

**Comment by mCodex** [comment]
I've tested this scenario in the example project. The error that you mentioned is:

![screencap-2020-07-28T175327 307Z](https://user-images.githubusercontent.com/5920613/88702854-537b5780-d0e2-11ea-8bb0-8508126adde1.png)

However, after dismissing this popup and clicking again on button that triggers setItem works perfectly.

**Comment by mCodex** [comment]
Fixed in #224
