### ISSUE TITLE
How to install keystore branch?

### ISSUE THREAD

**Issue by JeremyBradshaw7** [mCodex/react-native-sensitive-info#206]
Pardon my ignorance, but how exactly do you install the keystore branch, eg. using yarn? I want to start using this from the off rather than having the problem of trying to change it later.

**Comment by JeremyBradshaw7** [comment]
Is the right:

`yarn add git://github.com/mCodex/react-native-sensitive-info#keystore`

**Comment by mCodex** [comment]
It is totally right! :) Thanks for your feedback, I'll add it in our docs.

**Comment by JeremyBradshaw7** [comment]
Thanks
