### ISSUE TITLE
java.security.UnrecoverableKeyException: Failed to obtain information about key

### ISSUE THREAD

**Issue by maggialejandro-rp** [mCodex/react-native-sensitive-info#216]
We are having this issue on v5.5.1

android.security.KeyStoreException: Invalid key blob

<img width="472" alt="Screen Shot 2020-07-28 at 11 37 32" src="https://user-images.githubusercontent.com/50118796/88680310-bced6d00-d0c6-11ea-99e5-b3db157c3e28.png">

<details>
<pre>
0 = {StackTraceElement@11586} "android.security.keystore.AndroidKeyStoreProvider.loadAndroidKeyStoreSecretKeyFromKeystore(AndroidKeyStoreProvider.java:282)"
1 = {StackTraceElement@11587} "android.security.keystore.AndroidKeyStoreSpi.engineGetKey(AndroidKeyStoreSpi.java:98)"
2 = {StackTraceElement@11588} "java.security.KeyStore.getKey(KeyStore.java:1062)"
3 = {StackTraceElement@11589} "br.com.classapp.RNSensitiveInfo.RNSensitiveInfoModule.putExtraWithAES(RNSensitiveInfoModule.java:338)"
4 = {StackTraceElement@11590} "br.com.classapp.RNSensitiveInfo.RNSensitiveInfoModule.setItem(RNSensitiveInfoModule.java:173)"
5 = {StackTraceElement@11591} "java.lang.reflect.Method.invoke(Native Method)"
6 = {StackTraceElement@11592} "com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:371)"
7 = {StackTraceElement@11593} "com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:150)"
8 = {StackTraceElement@11594} "com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)"
9 = {StackTraceElement@11595} "android.os.Handler.handleCallback(Handler.java:790)"
10 = {StackTraceElement@11596} "android.os.Handler.dispatchMessage(Handler.java:99)"
11 = {StackTraceElement@11597} "com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:26)"
12 = {StackTraceElement@11598} "android.os.Looper.loop(Looper.java:164)"
13 = {StackTraceElement@11599} "com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:225)"
14 = {StackTraceElement@11600} "java.lang.Thread.run(Thread.java:764)"
</pre>
<summary>Stacktrace</summary>
</details>

#### Cause

<img width="715" alt="Screen Shot 2020-07-28 at 11 42 30" src="https://user-images.githubusercontent.com/50118796/88680972-73515200-d0c7-11ea-8854-54051e0eef95.png">

https://android.googlesource.com/platform/frameworks/base/+/master/keystore/java/android/security/KeyStore.java#1302
https://android.googlesource.com/platform/frameworks/base/+/master/core/java/android/security/keymaster/KeymasterDefs.java#193

**Comment by maggialejandro-rp** [comment]
@mCodex I'm not sure, can we handle this scenario the same way as a InvalidKeyException?

**Comment by mCodex** [comment]
@maggialejandro-rp I guess it could be a way. First, need to investigate where this exception is being thrown in RNSInfo. Do you get this error using which method?

**Comment by maggialejandro-rp** [comment]
@mCodex it throw the Exception when trying to get the key
https://github.com/mCodex/react-native-sensitive-info/blob/f911a12739366eeda44b2440ae21f7404d0563b4/android/src/main/java/br/com/classapp/RNSensitiveInfo/RNSensitiveInfoModule.java#L336

**Comment by mCodex** [comment]
Thanks. I guess we could try your idea and see if fixes the problem

**Comment by mCodex** [comment]
@all-contributors please add @maggialejandro for code and maintenance

**Comment by mCodex** [comment]
@maggialejandro-rp I've released your fix in [v6.0.0-alpha.2](https://github.com/mCodex/react-native-sensitive-info/releases/tag/v6.0.0) which keystore by default. 😉
