### ISSUE TITLE
[Question] Touch ID Required in setItem on Android?

### ISSUE THREAD

**Issue by duncan-iaria** [mCodex/react-native-sensitive-info#226]
On version `6.0.0-alpha.4` of this package and using Android, when I setItem it requires me to use `touchID: true` when I want to use touchID to get the item back out - otherwise I get a decryption error. 

From the user perspective that means that anytime we `setItem`, it requires them to use their fingerprint to confirm it. So, for example, if a user logs in with their fingerprint (we unlock the token and send it along), and we get a new token from the server and want to save that new token for the next time they log in, we require the user to user their fingerprint _again_ to confirm it.

That ends up being 2 fingerprints in a row to log in. Is that functionality the intent of the package? I noticed in a previous issue someone mentioned that you don't need to have `touchID` to setItem. That is technically true, but if you want to use the touchID to get it back out then you're in trouble.

**Comment by mCodex** [comment]
hey @duncan-iaria could you please provide a snippet from your setItem?
