### ISSUE TITLE
Post Android 11 fix to v5 branch

### ISSUE THREAD

**Issue by YOzaz** [mCodex/react-native-sensitive-info#250]
Related to this commit: https://github.com/mCodex/react-native-sensitive-info/commit/89dab8495821fb8d0a6169639fb068d81283c4a4

While v6 is in alpha stage, can you please port this (and others if necessary) to v5 version / branch please?

Related PR: https://github.com/mCodex/react-native-sensitive-info/pull/251

**Comment by mCodex** [comment]
Hi!

Of course! Done! Closing this issue for now :)
