### ISSUE TITLE
SetItem prompts user for face ID

### ISSUE THREAD

**Issue by TheMatrixMaster** [mCodex/react-native-sensitive-info#266]
Hello,

when I use setItem with the following configuration on IOS, I am prompted to authenticate with Face ID. 
```
SInfo.setItem('password', pass, {
    kSecAccessControl: 'kSecAccessControlBiometryAny',
    touchID: true, //add this key
    showModal: true, //add this key
    // required (iOS) -  A fallback string for iOS
    kSecUseOperationPrompt: 'Use face-id to re-authenticate',
    strings: {
        // optional (Android) - You can personalize your prompt
        description: 'Re-authenticate',
        header: 'Use fingerprint to retrieve login info',
    },
})
```

The expected behaviour is no prompts when using setItem and prompts when using getItem.

**Comment by Loxrie** [comment]
I have the opposite issue with the same code, and I want prompts for both. :/  Did you manage to get anywhere with this?  I note a common issue with this project is issues are left to go stale and then get auto closed with no resolution.

**Comment by TheMatrixMaster** [comment]
@Loxrie, unfortunately that seems to be the case. Instead of dwelling on this issue, I switched to a different package (react-native-keychain) that did the job for me.

**Comment by Loxrie** [comment]
I've just done the same, I have react-native-keychain in an older project alongside a separate library for biometric auth.  It seems react-native-keychain appears to now support both, so I'm giving it a whirl today.

**Comment by crzycoder** [comment]
prompt dialog is not showing when setItem to `Face ID` on IOS.
any progress
