### ISSUE TITLE
Return a promise from setItem?

### ISSUE THREAD

**Issue by globetro** [mCodex/react-native-sensitive-info#27]
As I understand it, `setItem` is actually asynchronous. Is it possible to update `setItem` to return a promise that's resolved when `setItem` has completed? I'm running into an issue on iOS where I get a `Could not locate shadow view with tag` error if I try to call `setState` immediately after calling `setItem`. It's fixed if I add an artificial delay of a few hundred milliseconds. According to this issue https://github.com/facebook/react-native/issues/7977, it seems related to trying to call `setState` before `setItem` is completed.

**Comment by mCodex** [comment]
Hello @globetro, we actually has already received an pull request #26 with your suggestion, but unfortunately I didn't have time to take a look yet. 

If you feel comfortable you can use our library using the pull request above.

Also, I'll try to release an update today with the mentioned pull request.

**Comment by mCodex** [comment]
Hi @globetro , how are you?

I'd like to thank you for your patience and tell you that I've just launched a new version (5.1.0) of our library with promise support on setItem. Please, feel free to update it to latest version 😄
