### ISSUE TITLE
Stored value in Keychain is undefined

### ISSUE THREAD

**Issue by Sunitadaffodil** [mCodex/react-native-sensitive-info#29]
Hello..

Thanks for this great library.
I am using this library in one of my react-native project, but whenever I am trying to get value stored in keychain , is returning undefined in iOS.

Here is what is my use case
1-We have an existing "Native iOS App", which is already present in AppStore to download.
2-Now my client is redeveloping the same app in React-Native, and want to provide this new app as an update to existing users.
3-So we are keeping "Bundle ID" of our new (react-native app) same as that of older app (iOS native app), with higher version number ,so that our new will be downloaded as an updated.
4-Let's suppose, an existing user is already logged in the older app, so we want to maintain this logged status , whenever user update app with newer one.
5-In older app (iOS native app), we are saving "Access Token" in keychain, so based on whether "Access Token" is present in keychain, we decide the logged in status of user
6-Now, in newer app (react-native), we have to get that same "Access Token" from keychain, so that we can decide the logged in status of user and can navigate the user to appropriate screen.

I hope that makes sense!

Now when I am using this library, and try to get "Access Token" from keychain, its returning "undefined" in iOS.

Here may be I am doing something wrong, which only you guys can figure out.
This is how I am trying to get saved "Access Token".

SInfo.getItem("AccessToken", {}).then(value => {
                alert(value);
                console.log("access token is", value);  // value1
            });

**Comment by mCodex** [comment]
Hello @Sunitadaffodil, well I developed react-native-sensitive-info because I had to do exactly what you described here, but in my case the app that I was migrating from native iOS to RN was using the default keychain service (which is: app) to store user's data.

Probably, you can check if your user's credentials are being stored using the default keychain service or another one and then try to get it using:

```javascript
SInfo.getItem('key1', {
   keychainService: YOUR_KEYCHAIN_HERE
}).then(value => {
    console.log(value) //value1
});
``` 

Because it is so strange to me 🤔

**Comment by Sunitadaffodil** [comment]
Thanks @mCodex for quick reply.

In iOS native project , its using PDKeychainBindingController library. This library helps in saving data to keychain.

But I am not sure whether its using default keychain to store data, because someone else worked on that project. But your point is valid , may be this library storing data in some other way.

To resolve this issue, I have to write down the native module, that will be responsible to get "Access Token" from keychain using that same library (PDKeychainBindingController) and returning back the result to my react-native code.

Let me know, if we can discuss this approach in detail, because I am still not confident of this approach, whether this is the right way to get this thing done.

Thanks again :-)

**Comment by mCodex** [comment]
Hello @Sunitadaffodil, I'm so sorry for the delay. Your approach is a good one, I was searching about PDKeychainBindingController on the web, but I couldn't find anything to help you and I've never used it before. If you feel free, It is possible to fork RNSenstiveInfo and adapt it to your necessities. :)
