### ISSUE TITLE
icloud shared keychain

### ISSUE THREAD

**Issue by evollu** [mCodex/react-native-sensitive-info#30]
if the items stored in this keychain shared in icloud?

**Comment by mCodex** [comment]
Hello @evollu , sorry for the delay, but I haven't tested it yet. When I built react-native-sensitive-info I didn't know much about iOS architecture and for the project that I've used it, it was not necessary.

**Comment by evollu** [comment]
It wasn't necessary for me as well. Just to make sure that users won't get surprise when they install the app on another device. I think it is not shared though.

**Comment by mCodex** [comment]
I see, it could be an enhancement. 😄
