### ISSUE TITLE
SetItem never resolves in Samsung A72 device

### ISSUE THREAD

**Issue by gabrielyoto** [mCodex/react-native-sensitive-info#302]
First of all, this is my workspace:
```
"react": "16.13.1",
"react-native": "0.63.3",
"react-native-sensitive-info": "^5.5.8",

Android version: 11
```

I tried the same sample in ASUS Zenfone 3 Max (Android 8) and it worked just fine, but when I try it in Samsung A72 device, the SetItem function never resolves.

```
console.log('before');
try {
  await RNSInfo.setItem('testone', 'Pass123123', {
    touchID: true,
    showModal: true,
    kSecAccessControl: 'kSecAccessControlBiometryAny',
  });
} catch (er) {
  console.log({ er });
}
console.log('after');
```
OUTPUT:
```
>before
```

it does not throw errors, neither resolves :(
Android native modal also does not show.

**Comment by thecodecafe** [comment]
I'm also experiencing this on Samsung Galaxy M11. @gabrielyoto, have you been able to find a solution?

**Comment by gabrielyoto** [comment]
@thecodecafe not yet, every time I try to use it in this device, I'm having this issue

**Comment by lukaszKowal-datasite** [comment]
This still seems to be an issue

**Comment by salockhart** [comment]
This appears to be resolved if I backport https://github.com/mCodex/react-native-sensitive-info/pull/238 to `5.5.8`

I see that it was pulled into the `v5.x` branch: https://github.com/mCodex/react-native-sensitive-info/commit/16512f69ee8bc83f55113b9fe0d4d3f65e8b216e but might not have been released.

I can maintain a patch on my side, but @mCodex would it be possible to get a patch release out for the head of the `v5.x` branch? Or, is the v6 release coming on the horizon?
