### ISSUE TITLE
how can i clear all data when ios app is uninstalled in redux-persist-sensitive-storage

### ISSUE THREAD

**Issue by jeevithaBA** [mCodex/react-native-sensitive-info#303]
I am using redux-persist-sensitive-storage. When I uninstall an app and then reinstall it, my old data still exists. How can I clear all data when uninstalling an ios app?

**Comment by stefblokdijk** [comment]
+1

**Comment by xhirazi** [comment]
+1

**Comment by akimabs** [comment]
+1

**Comment by crzycoder** [comment]
I'm using `redux-persist-sensitive-storage` for persist the user data but after uninstall the App on `IOS` it did not clear the data and reinstall it again it show that user is logged in.

**Comment by mysport12** [comment]
If you are using this with redux-persist-sensitive-storage and redux-persist what you can do is use the { manualPersist: true } config option from redux-persist.

`export const loadStore = async (setStoreReady: (boolean) => void) => {
  let persist = true
  try {
    let newInstallCheck: ?string = await AsyncStorage.getItem(storeVersion)
    if (newInstallCheck == null) {
      persist = false
    }
  } catch {
    persist = false
  }
  let persistor = persistStore(store, { manualPersist: true }, async () => {
    await AsyncStorage.setItem(storeVersion, 'yes')
    store.dispatch({ payload: { storePersisted: true }, type: 'set_appConfig' })
    setStoreReady(true)
  })
  if (!persist) {
    await persistor.purge()
    persistor.persist()
  } else {
    persistor.persist()
  }
}`

**Comment by mysport12** [comment]
Not sure if that is your particular use case but one way of clearing out persisted redux state

**Comment by crzycoder** [comment]
I found the solution and it worked .. You just have to add the following code in you `AppDelegate.m` `didFinishLunchingWithOptions` function.

`  if ([[NSUserDefaults standardUserDefaults] boolForKey:@"HAS_RUN_BEFORE"] == NO) {
    // Set the appropriate value so we don't clear next time the app is launched
    [[NSUserDefaults standardUserDefaults] setBool:YES forKey:@"HAS_RUN_BEFORE"];
    NSArray *secItemClasses = [NSArray arrayWithObjects:
                               (__bridge id)kSecClassGenericPassword,
                               (__bridge id)kSecClassInternetPassword,
                               (__bridge id)kSecClassCertificate,
                               (__bridge id)kSecClassKey,
                               (__bridge id)kSecClassIdentity,
                               nil];
    for (id secItemClass in secItemClasses) {
      NSDictionary *spec = @{(__bridge id)kSecClass: secItemClass};
      SecItemDelete((__bridge CFDictionaryRef)spec);
    }
   }`

**Comment by sLurPPPeRsTaR** [comment]
+1

**Comment by sLurPPPeRsTaR** [comment]
> I found the solution and it worked .. You just have to add the following code in you `AppDelegate.m` `didFinishLunchingWithOptions` function.
> 
> ` if ([[NSUserDefaults standardUserDefaults] boolForKey:@"HAS_RUN_BEFORE"] == NO) { // Set the appropriate value so we don't clear next time the app is launched [[NSUserDefaults standardUserDefaults] setBool:YES forKey:@"HAS_RUN_BEFORE"]; NSArray *secItemClasses = [NSArray arrayWithObjects: (__bridge id)kSecClassGenericPassword, (__bridge id)kSecClassInternetPassword, (__bridge id)kSecClassCertificate, (__bridge id)kSecClassKey, (__bridge id)kSecClassIdentity, nil]; for (id secItemClass in secItemClasses) { NSDictionary *spec = @{(__bridge id)kSecClass: secItemClass}; SecItemDelete((__bridge CFDictionaryRef)spec); } }`

@crzycoder Thanks man you saved me
