### ISSUE TITLE
Not working in Expo app

### ISSUE THREAD

**Issue by imsam67** [mCodex/react-native-sensitive-info#317]
I'm trying to use `react-native-sensitive-info` in an Expo app (SDK 42) and I keep getting the following error.

> _reactNativeSensitiveInfo.default.setItem is not a function

Here's how I'm trying to use it. This is a simple function I created in a util file. Interestingly, I actually used this exact code before in a React Native project that was created through the CLI and it worked fine.
```
export const saveAuthenticationData = async (access_token, refresh_token, expiresIn) => {
   return await SInfo.setItem('auth', JSON.stringify({accessToken: access_token, refreshToken: refresh_token, expiresIn: expiresIn}), {});
};
```

Is `react-native-sensitive-info` not compatible with Expo or is there another problem?

**Comment by Raduc4** [comment]
Any updates?
