### ISSUE TITLE
Occasional "PasswordVault The system cannot find the path specified." error when storing data

### ISSUE THREAD

**Issue by juhasuni** [mCodex/react-native-sensitive-info#318]
The Windows implementation gives occasional errors with full error description of:

> ERROR SAVE PasswordVault The system cannot find the path specified.

The error "The system cannot find the path specified" indicates that the PasswordVault file might be somehow missing or alternatively it is locked by another operation.

Both c++ and c# implementations initialize a new PasswordVault instance upon reading or writing data. My theory is, that upon writing data the PasswordVault file is locked and if you end up invoking two write operations simultaneously, you'll get the error.

Packages installed

```
"react-native-sensitive-info": "^6.0.0-alpha.9"
"react-native": "0.65.1"
"react-native-windows": "0.65.4"
```

**Comment by tero-paananen** [comment]
It seems that we have solution for that issue.

We create one instance of `const Windows::Security::Credentials::PasswordVault PasswordVault = Windows::Security::Credentials::PasswordVault();` PasswordVault object and use that same instance on all methods.

We will send PR later for this.
