### ISSUE TITLE
add support kSecAttrAccessible

### ISSUE THREAD

**Issue by iamai74** [mCodex/react-native-sensitive-info#32]
Please, add support kSecAttrAccessible in setItem (iOS). By default the value of the attribute is kSecAttrAccessibleWhenUnlocked. But sometimes it is required to use other value, for example in TodayExtension need to use value kSecAttrAccessibleAlways

**Comment by mCodex** [comment]
Hello @iamai74, thank you! I'll see what I can do. If you want, you can submit a pull request =)

**Comment by evollu** [comment]
I'm working on it

**Comment by iamai74** [comment]
@mCodex, oh's good pr from @umer98. I think it will works for me/

**Comment by mCodex** [comment]
@iamai74. Its nice to hear it from you! :D I'll close the issue for now, but if its needed you can reopen it again :D
