### ISSUE TITLE
"The user name or passphrase you entered is not correct" on passcode fallback (iOS)

### ISSUE THREAD

**Issue by Zykhatslover** [mCodex/react-native-sensitive-info#323]
Every time I try to login with the fallback passcode on iOS (tried on both 15+ and 14.x versions of iOS), I get prompted with an error "The user name or passphrase you entered is not correct", while the passcode is correct.

I'm using the `6.0.0-alpha.9` version of the package, and I tried with the example provided in the package, so it looks like `errSecAuthFailed` is returned whenever I input the correct device passcode.

**Comment by Ganesh-softsuave** [comment]
Still facing the issue

**Comment by Zykhatslover** [comment]
Same here, but we decided to go for another library since this one is not meeting our requirements.  I'd advise you to do the same.

**Comment by Ganesh-softsuave** [comment]
Which library you are going to use ?

**Comment by Zykhatslover** [comment]
We went for https://github.com/oblador/react-native-keychain :-)

**Comment by Ganesh-softsuave** [comment]
Even this package is facing this issue.There they have mentioned its due to IOS 15 https://github.com/oblador/react-native-keychain/issues/509

**Comment by gabrielmoncea** [comment]
happening to me too
