### ISSUE TITLE
After uninstall and install app stored information remained (IOS)

### ISSUE THREAD

**Issue by Melber17** [mCodex/react-native-sensitive-info#324]
I'm using the 6.0.0-alpha.9 version of the package

**Comment by crzycoder** [comment]
any improvement ??

**Comment by crzycoder** [comment]
try this code in `AppDelegate.m` `didFinishLaunchingWithOptions`

`  if ([[NSUserDefaults standardUserDefaults] boolForKey:@"HAS_RUN_BEFORE"] == NO) {`
    `[[NSUserDefaults standardUserDefaults] setBool:YES forKey:@"HAS_RUN_BEFORE"];`
    `NSArray *secItemClasses = [NSArray arrayWithObjects:`
    `                           (__bridge id)kSecClassGenericPassword,`
    `                           (__bridge id)kSecClassInternetPassword,`
    `                           (__bridge id)kSecClassCertificate,`
    `                           (__bridge id)kSecClassKey,`
    `                          (__bridge id)kSecClassIdentity,`
    `                          nil];`
    `for (id secItemClass in secItemClasses) {`
     `NSDictionary *spec = @{(__bridge id)kSecClass: secItemClass};`
    ` SecItemDelete((__bridge CFDictionaryRef)spec);`
    `}`
   `}`

**Comment by Melber17** [comment]
It's working! 
Thank you!

> try this code in `AppDelegate.m` `didFinishLaunchingWithOptions`
> 
> ` if ([[NSUserDefaults standardUserDefaults] boolForKey:@"HAS_RUN_BEFORE"] == NO) {` `[[NSUserDefaults standardUserDefaults] setBool:YES forKey:@"HAS_RUN_BEFORE"];` `NSArray *secItemClasses = [NSArray arrayWithObjects:` ` (__bridge id)kSecClassGenericPassword,` ` (__bridge id)kSecClassInternetPassword,` ` (__bridge id)kSecClassCertificate,` ` (__bridge id)kSecClassKey,` ` (__bridge id)kSecClassIdentity,` ` nil];` `for (id secItemClass in secItemClasses) {` `NSDictionary *spec = @{(__bridge id)kSecClass: secItemClass};` ` SecItemDelete((__bridge CFDictionaryRef)spec);` `}` `}`
