### ISSUE TITLE
[IOS] Protected data not available yet. Retry operation

### ISSUE THREAD

**Issue by Miyagee** [mCodex/react-native-sensitive-info#326]
We started to get a lot of `Protected data not available yet. Retry operation` from our ios users. 

It is happening for ios users above 14.6 while the majority of the problems come from ios 15.x. Does anyone know what could be causing the problem? We're on `6.0.0-alpha.9`

**Comment by BogdanRad** [comment]
I have the same problem.. did you find a solution @Miyagee?

**Comment by Miyagee** [comment]
Not really, we reduced our number of concurrent async operations which reduced the occurrences. But they still occur.

**Comment by rubytes** [comment]
I've suddently started getting this error too, even though I have not updated my codebase

**Comment by rubytes** [comment]
I'm also still getting this error. Any updates yes?

**Comment by sofia-bahamonde** [comment]
I'm also getting this error. Any updates?

**Comment by ricardodolnl** [comment]
So, any updates? Because I'm still experiencing this issue and I did expect some updates after more than a year to be honest.

**Comment by sourabhdadapure** [comment]
Currently facing the same issue and @Pickleboyonline I don't think the post you have suggested is related to this issue. This issue is related to background capability of the app

**Comment by ricardodolnl** [comment]
@sourabhdadapure i found this in the code https://github.com/mCodex/react-native-sensitive-info/blob/495dd7f08c077f5744e56803e45f54787df3dab3/ios/RNSensitiveInfo/RNSensitiveInfo.m#L261 and that made me think of catching the error and just retrying to get the data. It's not the cleanest solution but it does work for now:
```javascript
let getDataAttempts = 0;

const getUserData = async () => {
  try {
    const refreshToken = await SInfo.getItem('refreshToken', {});
  } catch (e) {
    if (e.code === 'protected_data_unavailable') {
      if (getDataAttempts < 10) {
        // Retry getting item after 300ms for max 10 attempts.
        setTimeout(() => {
          getUserData();
        }, 300);
      } else {
        // Do something after 10 failed attempts, like logging out.
      }

      getDataAttempts++;
    }
  }
};
```

**Comment by millro04** [comment]
Re-pinging this thread to see if there's any update here?

**Comment by ftlno** [comment]
Any news here?

**Comment by kamiranoff** [comment]
This is related to this issue: https://github.com/mCodex/react-native-sensitive-info/issues/283

Anyone knows how to reproduce this locally?
