### ISSUE TITLE
Storage size

### ISSUE THREAD

**Issue by gabimoncha** [mCodex/react-native-sensitive-info#329]
Hello!

Does anyone know what's the value size limit for a stored item?

I'm looking to switch away from [expo-secure-storage](https://docs.expo.dev/versions/latest/sdk/securestore#:~:text=Size%20limit%20for%20a%20value,store%20larger%20values%20may%20fail.) because of it's 2048 bytes size limit per stored value

**Comment by gabrielmoncea** [comment]
@mCodex is this project still maintained?
