### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by ognjetina** [mCodex/react-native-sensitive-info#34]
Could you review examples it seems like that they take 94.5MB

**Comment by mCodex** [comment]
Hello @ognjetina, thank you! I'll see it for u =)

**Comment by vspedr** [comment]
@mCodex we could add a `.npmignore` to the project root, excluding the `/example` folder from the package but keeping it in version control.

**Comment by mCodex** [comment]
@vspedr, yeah! It seems a good idea. Tonight i'll do it :+1:

**Comment by vspedr** [comment]
Check this out, there are a few things to keep in mind with a `.npmignore`
https://docs.npmjs.com/misc/developers#keeping-files-out-of-your-package

**Comment by vspedr** [comment]
Hey @ognjetina this should now be fixed in 76b38f1, examples folder will no longer be downloaded from npm.

**Comment by ognjetina** [comment]
yey :D

**Comment by mCodex** [comment]
@ognjetina, I'll close the issue for now, but if its needed you can reopen it again :D
