### ISSUE TITLE
is react-native-senstive-info Asynchronous or Synchronous?

### ISSUE THREAD

**Issue by j3rin** [mCodex/react-native-sensitive-info#42]
constructor(){
      super();
      this.state = {loggedIn: false};
      SInfo.getItem('token', {
      keychainService: 'myKeychain'}).then(value => {
        if(value){
          fetch('api/ping',{
                method: 'GET',
                headers: {'Authorization': value}
          })
          .then((responseJson) => {
            if(responseJson.status == 200){
                this.setState({loggedIn : true})
            }else{
                this.setState({loggedIn : false})
            }
          })
          .catch((error) => {
              alert(error);
          })
        }else{
            this.setState({loggedIn : false})
        }
      });
    }

Is there any way I can make this function wait until I get success from api?

**Comment by ugiacoman** [comment]
It is async, you can use async/await

**Comment by mCodex** [comment]
I hope your doubt was solved, if u need any kind of help just reopen this issue or create a new one 😄
