### ISSUE TITLE
Error when install module no compatible with RNGoogleSignin

### ISSUE THREAD

**Issue by mealbarracin10** [mCodex/react-native-sensitive-info#44]
i try integrate this module, when install it,  modified this file project.pbxproj,  and produced error i dont open this app by  xcode, not parse this project 

this installation write this
HEADER_SEARCH_PATHS = "$(SRCROOT)/../node_modules/react-native-google-signin/ios/RNGoogleSignin/**""$(SRCROOT)/../node_modules/react-native-sensitive-info/ios/RNSensitiveInfo/**";

in this case produced error but form correct could so : 

HEADER_SEARCH_PATHS = ("$(SRCROOT)/../node_modules/react-native-google-signin/ios/RNGoogleSignin/**",
"$(SRCROOT)/../node_modules/react-native-sensitive-info/ios/RNSensitiveInfo/**");

**Comment by evollu** [comment]
sounds like a link issue rather than this repo

**Comment by mCodex** [comment]
@mealbarracin10 it is a strange error 🤔  

We can try to reproduce that generating a new project and installing both libraries
