### ISSUE TITLE
IOS does not clear Keychain once the app uninstalls

### ISSUE THREAD

**Issue by AunMSheikh** [mCodex/react-native-sensitive-info#45]
I noticed an issue when uninstalling the application the data does not get deleted, is there any way to remove data when the app uninstalls?

**Comment by evollu** [comment]
that seems to be expected behavior as keychain. check ios keychain question on stackoverflow ?

**Comment by mCodex** [comment]
@AunMSheikh Unfortunately, it doesn't remove, but could be a future feature in RNSInfo.

**Comment by pongponglau** [comment]
Yes, i have the same issue as AunMSheikh.
But not sure if react native has an uninstall app event. If so, i can remove the keychain value when this event comes.

Thank you

**Comment by felixus95** [comment]
It shouldn't in my opinion. We use it exactly for this use case. Keychain stores data to identify users, who reinstalled the application.

**Comment by mCodex** [comment]
@felixus95 has a great point of view. And I agree with him. Since then, I'll close this issue now. Maybe It can be opened in the near future for more discussions.

**Comment by Melber17** [comment]
After uninstall and install app stored information remained.
