### ISSUE TITLE
does not work with CRNA / Expo

### ISSUE THREAD

**Issue by Morriz** [mCodex/react-native-sensitive-info#50]
Hi, any idea why I can't seem to import your module with a fresh CRNA install?

```
import SInfo from 'react-native-sensitive-info'

console.log('SInfo: ', SInfo)
```
console output:
`SInfo:  undefined`

I use:
```
"dependencies": {
    "expo": "^21.0.0",
    "react": "16.0.0-alpha.12",
    "react-native": "^0.48.4",
    "react-native-sensitive-info": "^5.1.0"
  }
```

**Comment by vspedr** [comment]
Hi @Morriz! Did you get this behavior on Android or iOS? Usually when a module with native code returns undefined it's because it was not linked properly with the native projects, you can try running `react-native link react-native-sensitive-info` again or linking it manually. I'm not very familiar with expo though, not sure how it handles external native dependencies.

**Comment by Morriz** [comment]
I did that already, but to no avail. It would be awesome if your module would work with CRNA out of the box, but you probably have to do some tweaking. I would reach out to the CRNA ppl if I were you.

**Comment by Morriz** [comment]
I always test on physical device btw

**Comment by vspedr** [comment]
Yes, that would be nice given the popularity of CRNA. I will look into it this weekend, maybe @mCodex can give it a try too

**Comment by mCodex** [comment]
@Morriz thank you for letting us know about this problem. I'll take a look :)

**Comment by Morriz** [comment]
:)

**Comment by Palisand** [comment]
@mCodex @Morriz **You cannot use any modules that require linking (i.e. native modules) with expo.** You must either detach to ExpoKit or eject completely. See [this](https://docs.expo.io/versions/latest/guides/detach.html#you-might-want-to-detach-if).

Please note that Expo SDK 21 already has a [SecureStore](https://docs.expo.io/versions/latest/sdk/securestore.html).

**Comment by vspedr** [comment]
Thanks for clarifying @Palisand!

**Comment by Morriz** [comment]
Yes, tnx! That new SecureStore is exactly what I need :)

**Comment by mCodex** [comment]
Thanks @Palisand 👍 I'll close this issue for now since @Morriz found the solution 👍

**Comment by marudhupandiyang** [comment]
I encountered the same issue with `react-native init` project on ios. The auto linking did not work. I had to manually link to get this working.

**Comment by vspedr** [comment]
@marudhupandiyang could you please open a new issue for that and provide more detail (RN version, iOS version etc.)?
