### ISSUE TITLE
Add Windows to npm release

### ISSUE THREAD

**Issue by antondomratchev** [mCodex/react-native-sensitive-info#51]
Pulled down latest version 5.1.0 from NPM, and the entire windows directory is missing.
Any idea if RN Windows support is working?
When can we expect a release with Windows code in NPM?

**Comment by mCodex** [comment]
Hello @antondomratchev , sorry for delaying the answer, but you can test it by installing a beta version of RNSensitiveInfo. I've just released it 😄 

```bash
yarn add react-native-sensitive-info@5.2.0
```

**Comment by antondomratchev** [comment]
@mCodex Thanks! I 've been using the master branch in the project and so far its working great!

I noticed that in Windows `getAllItems()` will throw an exception if no credentials are found for the given SharedPreference/KeychainService. Not sure if the behavior is the same for both iOS and Android.

Thank you for the updated release!

**Comment by mCodex** [comment]
@antondomratchev thank you for your feedback! I'm glad you're using a beta version now. The most important thing is to know Windows Phone is working like a charm! 😃
