### ISSUE TITLE
Question about 5.0 and Android KeyStore

### ISSUE THREAD

**Issue by titkov5** [mCodex/react-native-sensitive-info#57]
Hi guys, first of all sorry for issue (i just don't know how i can ask you another way). I want to use Android KeyStore but now i see that this changes not in npm repo. So i want to ask about your plans for KeyStore, will you release this feature? Thank you for any answers!

**Comment by eranbaroz** [comment]
@titkov5 you can fetch a specific branch code with npm:
npm i -S git://github.com/mCodex/react-native-sensitive-info#keystore

**Comment by Cavitt** [comment]
@eranbaroz out of curiosity why are Shared Preferences the default?

**Comment by eranbaroz** [comment]
Hi @Cavitt 
Well, I'm not the module author and I don't know what exactly is behind setting the shared prefs as default.
I was just answering a question that related to fetching a specific repository version from package.json using npm.

Maybe you should ask again one of the authors.

Cheers

**Comment by eranbaroz** [comment]
@Cavitt 
By the way I was exploring some modules to use the keystore/keychain in react native. This was one of the modules I checked but decided to go with another one in the end.

**Comment by mCodex** [comment]
Hey guys! @Cavitt when I built this module, I needed to get information stored by native (Java / Object-C) app into the Shared Preferences / Keychain. It was it :)

**Comment by kashkama** [comment]
> @titkov5 you can fetch a specific branch code with npm:
> npm i -S git://github.com/mCodex/react-native-sensitive-info#keystore

can I do this with yarn?
> yarn add git://github.com/mCodex/react-native-sensitive-info#keystore
