### ISSUE TITLE
deleteItem gives error: Cannot read property 'then' of undefined

### ISSUE THREAD

**Issue by bbhagat** [mCodex/react-native-sensitive-info#63]
Hi,

I have below code which is called on press of a button.

`onLogoutPressed = () => {
console.log('Logout Pressed');
    SInfo.deleteItem('token', {})
    .then((values) => {
      console.log('deleted')
    });
    console.log('Logout Pressed 2');
}`

It gives me below error always:

> **Cannot read property 'then' of undefined.** 
> Object.MessageScreen._this._onLogoutPressed [as on Press]
> MessageScreen.js:30:5

It seems to me that deleteItem doesn't return a Promise. 

How can I make a call to another function after ensuring that item is deleted?

Regards,
Bhavik

**Comment by michaeljholmes** [comment]
+1

**Comment by michaeljholmes** [comment]
Simple fix :
Promise.resolve(SInfo.deleteItem(key, options))
