### ISSUE TITLE
Touch ID prompt is not shown when set item in keychain.

### ISSUE THREAD

**Issue by giriprathap** [mCodex/react-native-sensitive-info#71]
Hi 

This issue is with the iOS.

My SetItem code is 
 SInfo.setItem('hashPassword', hashPassword.toString(), {
    keychainService: 'myKeychain',
    kSecAccessControl: 'kSecAccessControlTouchIDCurrentSet',
    sharedPreferencesName: 'mySharedPrefs',
    touchID: true,
  });

My getItem code is 

 SInfo.getItem('hashPassword', {
      sharedPreferencesName: 'mySharedPrefs',
      keychainService: 'myKeychain'}).then(value => {
          }
      });

Issue is , when i try to get the hashPassword , OS is not prompting any Touch ID for me.

I did a code walk through , there is a difference between your example code and the library code in mainly in "RNSensitiveInfo" class there is no Touch ID related code.

can you please update this ASAP.

**Comment by iSachdeva** [comment]
@giriprathap  Did you figure out the solution of above problem? I am also facing the same issue.
Appreciate on any help, Thanks.

**Comment by iSachdeva** [comment]
@giriprathap  Yes it worked. Thanks.

**Comment by anagar23** [comment]
@giriprathap , I am using 5.3.0 version of the library but not able to get the Touch ID pop while setting the key in Keychain.

In Android, it's working nicely.

`static setItem(key, value) {
    return sInfo.setItem(key, value, {
      keychainService: keyChainServiceName,
      kSecAccessControl: 'kSecAccessControlTouchIDCurrentSet',            
      touchID: true,
      showModal:true,
      sharedPreferencesName: 'Test',
    }).then((value) => {
      return value;
    }).catch((error) => {      
      console.log('error in setItem method in Keychain ' + error);
      return error;
    });
  }`

**Comment by krutkowski86** [comment]
I've got the same issue. When using setItem on iOS, there is no promt for user authentication. Any update?

**Comment by navin-d97** [comment]
I am also facing the same issue in latest version, 5.5.8. any updates?
