### ISSUE TITLE
Losing Data on IOs

### ISSUE THREAD

**Issue by obsidianart** [mCodex/react-native-sensitive-info#72]
Hi,
I don't know if that's a common issue or not but I had a few users reporting a total loss of their data on IOs after updating the OS or updating apps.
It might be something in my code but maybe you get similar problems in the past and it is a known issue.
(I have over 10k users on Android and no issue reported so it seems IOs only)

**Comment by artegen** [comment]
Hi, have this issue too. 
Appears only on iphone X (didn't try for iOS 11 on other devices). 
The data is lost when app is closed. When app is in background, turning back retrieves data from the storage correctly.

**Comment by mCodex** [comment]
As far as I can see it might be related to iOS 11 maybe. Unfortunately, I don't have an app to test it right now. :/

**Comment by lchapoy** [comment]
I am Facing the same issue. 
I have a react-native application with sentry:
- There are multiple issues for "unauthorized request", doing some research I found that the auth token is undefined and all the users having this problem are using either iPhone X or iPhone 8. 11.4 OS.
- The token is retrieved directly for the rn-sensitive-info get item method.

Do you guys figure out how to solve this issue?

Another important point, I have an iPhone X as well, I was doing some testing to try to reproduce the issue but I was unable to do it, the only difference is that I have 12 or higher OS. So the issue might be related to 11.X OS.

**Comment by arindam89** [comment]
We are facing the same issue, we are using it in Redux for iOS and Android and in iOS 11.4.1 and onwards, the sensitive info is not present after link 15 hours or so and the application logs out the user.

It works fine for iOS lower versions and Android. Please let us know how to debug and how to proceed.

Thanks in Advance.

**Comment by michaelcsilva** [comment]
I may be seeing this too on iOS, often shortly after app startup.  Killing and restarting the app seems to resolve the issue.  It's very inconsistent, but I see it in my own testing about 1 time per week, running the app on iOS in production mode (i.e. not attached to a debugger).  

The bug indicates help is needed.  What can I enable in terms of logging, alerts, etc. to help debug?

**Comment by kellycampbell** [comment]
Seeing this as well. Further searching turned up this issue thread: https://github.com/evgenyneu/keychain-swift/issues/78

I will try to implement the solution suggested in this comment: https://github.com/evgenyneu/keychain-swift/issues/78#issuecomment-495959391
