### ISSUE TITLE
RNSensitiveInfoModule's  getAllItems method returning error (keystore branch)

### ISSUE THREAD

**Issue by igorrfc** [mCodex/react-native-sensitive-info#73]
## Context

An Android user of a RN app that I work on is receiving the following error:
![error](https://user-images.githubusercontent.com/7783787/39211573-7031f5cc-47e2-11e8-8b14-85dcb3970173.png)

## Cause(?)

I tried to reproduce it just mirroring both app and OS versions, but wasn't lucky. Then I dove at the lib's source code looking for the `getAllItems` trying to understand it. I think that for some reason, at the [decrypt](https://github.com/mCodex/react-native-sensitive-info/blob/keystore/android/src/main/java/br/com/classapp/RNSensitiveInfo/RNSensitiveInfoModule.java#L123) stage of this method, one of the entries value is null at this user device.(I forced a null as the `decrypt` parameter and got the very same error)

Could you guys help me with this? Either pointing what went wrong at this device or checking if it is a missing validation at the `getAllItems` method.

## Device info
- brand: Lenovo;
- OS: Android;
- os version: 5.1.1;

LKM if you guys need more info. Thanks in advance!

**Comment by luisfmsouza** [comment]
Looks like the `getMessage()` was called from a `null`.

What's the chance of the `e.getCause()` inside the statement below resolve to a `null` value?

```js
catch (Exception e) {
  Log.d("RNSensitiveInfo", e.getCause().getMessage());
}
```

If it resolves to a `null`, does anyone know how to handle it to avoid this exception mentioned by @igorrfc?

**Comment by igorrfc** [comment]
That's true, @luisfmsouza. Good catch.
The `getMessage` method is used when the exception comes from a chain of exceptions, it returns the original/root cause of the error. Looks like there is a validation that isn't well handled and does not return an exception with a cause. Then, when the cause is not defined, the `getCause` returns null.

**Comment by mCodex** [comment]
Since the PR is merged. I'll close this issue.
