### ISSUE TITLE
[Android]Key permanently invalidated when a new fingerprint is enrolled

### ISSUE THREAD

**Issue by ycai2** [mCodex/react-native-sensitive-info#75]
This is Android only.
When I added a new fingerprint on system setting, the library now permanently fails authentication including calling of `setItem`. The error I received is "Key permanently invalidated". According to Android [doc](https://developer.android.com/training/articles/keystore#ExtractionPrevention):
> These keys become permanently invalidated once a new fingerprint is enrolled or all fingerprints are unenrolled.

It looks like in that case, the module will not work anymore, ever maybe? I'm not an Android developer, and maybe I'm misunderstanding the code. Can anyone help me understand this? Wether this is a bug or not?

Thanks

**Comment by Rovack** [comment]
This is a pretty significant issue, which it seems would prevent anyone from safely using this library on Android.
No comments on this?

**Comment by mCodex** [comment]
It sounds like a bug 🤔

**Comment by ycai2** [comment]
@mCodex I made a PR with the fix. Please review when you get a chance.

**Comment by ycai2** [comment]
#81 was merged to fix this.
