### ISSUE TITLE
[Question] About when app is uninstalled

### ISSUE THREAD

**Issue by akiradeveloper** [mCodex/react-native-sensitive-info#77]
I want to use this library to save device unique id (like ANDROID_ID). In PlayFab, there is a log-in method that use the unique id and the doc recommends to save it in key chain in case of iOS because the id is changed after app uninstalled. (see best practice section in https://api.playfab.com/docs/tutorials/landing-players/best-login)

As long as I understand, the shared preference is gone after app uninstalled unless the backup is enabled (and it's enabled by default). My question is how about key chain in iOS? the data is gone after app uninstalled?

**Comment by mCodex** [comment]
I'm not an expert on iOS, but I think when your user uninstalls the app, the data from keystore will be destroyed. 🤔

**Comment by petrkrizek** [comment]
On iOS encrypted data persists.

**Comment by jkdf2** [comment]
Yes, for most versions of iOS, the keychain data persists. Further reading with some possible workarounds mentioned here: https://forums.developer.apple.com/thread/36442
