### ISSUE TITLE
Same sharedPreferencesName between 2 apps on the phone

### ISSUE THREAD

**Issue by obsidianart** [mCodex/react-native-sensitive-info#78]
I'm trying to debug a problem on IOs only where a user lost all his data. I know there are many moving parts but while going trough the code (I can't replicate the issue) I wondered what happens if another application use the same "sharedPreferencesName" on the same phone.
I assume nothing happens but maybe you get another app info encrypted or something like that.
Do you have any idea? should I try to build a second app on the simulator?
Thanks,
Stefano

**Comment by mCodex** [comment]
Hey Stefano, unfortunately I have no idea. If you fix it, please share your solution here.

**Comment by obsidianart** [comment]
Of course I will, unfortunately I don't have an iPhone so even testing this is hard, maybe I should buy one.
