### ISSUE TITLE
App crashing:unrecognized selector sent to instance

### ISSUE THREAD

**Issue by shashikiran797** [mCodex/react-native-sensitive-info#85]
iOS versions: 11.3 and 11.4
react-native-sensitive-info versions: 5.1.0

My code
```javascript
const keyNameSpace = {
  sharedPreferencesName: 'xyz',
  keychainService: 'xyz',
};
const migrationDone = await SInfo.getItem('migrationDone', keyNameSpace);
```

Exception logs

```
RCTFatalException: Exception '-[__NSSingleObjectArrayI localizedDescription]: unrecognized selector sent to instance 0x1c02081a0' was thrown while invoking getItem on target RNSensitiveInfo with params ( migrationDone, { keychainServic: Exception '-[__NSSingleObjectArrayI localizedDescription]: unrecognized sel...
```

**Comment by denissb** [comment]
@shashikiran797 - can you paste the code of how you do `setItem`? I am assuming you provide a different configuration when calling it so there is a misalignment.

**Comment by fdnhkj** [comment]
After investigating into this issue, I can reproduce the error by forcing the app to reach this line:
https://github.com/mCodex/react-native-sensitive-info/blob/master/ios/RNSensitiveInfo/RNSensitiveInfo.m#L100

Question would be which error is making the `messageFromError` method fallback on the default case.
```
    default:
      return error.localizedDescription;
```

**Comment by denissb** [comment]
After taking a closer look it seems that in case any of the errors defined in `messageForError` method are encountered the app crashes with ```RCTFatalException: Exception '-[__NSSingleObjectArrayI localizedDescription]:```, in stead the promise should simply be rejected.

**Comment by denissb** [comment]
@shashikiran797  - this is fixed in version 5.2.0. Before the module was crashing the app on iOS for any encountered error intentionally with `RCTMakeAndLogError`.

**Comment by felixus95** [comment]
@denissb So when will it be released to npm? Version is still at 5.1.0

**Comment by felixus95** [comment]
The pre-release is dated back to October '17 and there is a newer version (5.2.1), so the package should be updated on npm, right? @mCodex

**Comment by denissb** [comment]
@felixus95, it is released, just in beta (npm shows last release). I tried it and it seems to work quite well.
