### ISSUE TITLE
iOS: Invalid typings for RNSensitiveInfoOptions?

### ISSUE THREAD

**Issue by jussirantala** [mCodex/react-native-sensitive-info#95]
**react-native-sensitive-info@5.2.4 and typescript@2.7.2**

None of the options in _RNSensitiveInfoOptions_ interface is optional and the options are not documented. How do I get _setItem_ working on iOS? I don't know how to configure it.

```
export interface RNSensitiveInfoOptions {
  kSecAccessControl: RNSensitiveInfoAccessControlOptions;
  kSecAttrAccessible: RNSensitiveInfoAttrAccessibleOptions;
  keychainService: string;
  kSecUseOperationPrompt: string;
  sharedPreferencesName: string;
  touchID: boolean;
}
```

The error I get with an empty configuration:
`  Property 'kSecAccessControl' is missing in type '{}'.`
Documentation says there should be a default value for _kSecAccessControl_.

**Comment by skurgansky-sugarcrm** [comment]
getAllItems should return Object but i'm getting on iOS
```
{
    key: string;
    value: string;
    keychainService: string
}[][]
```
on Android `{ [key: string]: string }` ???
